#!/usr/bin/env python3
"""Generate traceability matrix from HLRD and per-library LLRD requirements."""

from __future__ import annotations

from pathlib import Path


def parse_simple_yaml(text: str) -> dict:
    out: dict = {}
    current_key: str | None = None
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("- ") and current_key:
            out.setdefault(current_key, [])
            if isinstance(out[current_key], list):
                out[current_key].append(stripped[2:].strip().strip("'").strip('"'))
            continue
        if ":" not in stripped:
            continue
        key, value = stripped.split(":", 1)
        key = key.strip()
        value = value.strip().strip('"')
        current_key = key
        if value.startswith("[") and value.endswith("]"):
            items = [x.strip().strip("'").strip('"') for x in value[1:-1].split(",") if x.strip()]
            out[key] = items
        elif value:
            out[key] = value
        else:
            out[key] = []
    return out


def main() -> int:
    root = Path(__file__).resolve().parents[2]
    hlrd_dir = root / "certification" / "requirements"
    llrd_root = root / "certification" / "libraries"
    out = root / "certification" / "traceability" / "VRP-RTM-001.md"

    rows = [
        "# VRP-RTM-001 — Requirements Traceability Matrix",
        "",
        "Auto-generated by `Tools/cert/gen_traceability.py`.",
        "",
        "## High-Level Requirements (HLRD)",
        "",
        "| Req ID | DAL | Module | Verify | Tests |",
        "|---|---|---|---|---|",
    ]

    for req_file in sorted(hlrd_dir.glob("VRP-HLRD-*.yaml")):
        req = parse_simple_yaml(req_file.read_text())
        tests = req.get("tests", [])
        test_str = ", ".join(tests) if isinstance(tests, list) else str(tests)
        rows.append(
            f"| {req.get('id', '')} | {req.get('dal', '')} | {req.get('module', '')} | "
            f"{req.get('verify', '')} | {test_str} |"
        )

    rows.extend(
        [
            "",
            "## Low-Level Requirements — Libraries (LLRD)",
            "",
            "| Req ID | Parent | DAL | ArduPilot | VRP Module | Status | Phase | Verify |",
            "|---|---|---|---|---|---|---|---|",
        ]
    )

    for llrd_file in sorted(llrd_root.glob("*/VRP-LLRD-*.yaml")):
        req = parse_simple_yaml(llrd_file.read_text())
        rows.append(
            f"| {req.get('id', '')} | {req.get('parent', '')} | {req.get('dal', '')} | "
            f"`{req.get('ap_equivalent', '')}` | `{req.get('vrp_module', '').split('/')[-1]}` | "
            f"{req.get('status', '')} | {req.get('phase', '')} | {req.get('verify', '')} |"
        )

    dal_summary: dict[str, int] = {}
    for llrd_file in llrd_root.glob("*/VRP-LLRD-*.yaml"):
        req = parse_simple_yaml(llrd_file.read_text())
        dal = req.get("dal", "?")
        dal_summary[dal] = dal_summary.get(dal, 0) + 1

    rows.extend(
        [
            "",
            "## Riepilogo DAL librerie",
            "",
            "| DAL | Conteggio |",
            "|:---:|---:|",
        ]
    )
    for dal in sorted(dal_summary.keys()):
        rows.append(f"| {dal} | {dal_summary[dal]} |")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(rows) + "\n")
    print(f"written: {out} ({len(list(llrd_root.glob('*/VRP-LLRD-*.yaml')))} LLRD rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
