#!/usr/bin/env python3
"""Generate traceability matrix from HLRD, LLRD, MLRD, and test cases."""

from __future__ import annotations

from pathlib import Path


def parse_simple_yaml(text: str) -> dict:
    out: dict = {}
    current_key: str | None = None
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("- ") and current_key:
            out.setdefault(current_key, [])
            if isinstance(out[current_key], list):
                out[current_key].append(stripped[2:].strip().strip("'").strip('"'))
            continue
        if ":" not in stripped:
            continue
        key, value = stripped.split(":", 1)
        key = key.strip()
        value = value.strip().strip('"')
        current_key = key
        if value.startswith("[") and value.endswith("]"):
            items = [x.strip().strip("'").strip('"') for x in value[1:-1].split(",") if x.strip()]
            out[key] = items
        elif value:
            out[key] = value
        else:
            out[key] = []
    return out


def main() -> int:
    root = Path(__file__).resolve().parents[2]
    hlrd_dir = root / "certification" / "requirements"
    llrd_root = root / "certification" / "libraries"
    mlrd_root = root / "certification" / "modules"
    tc_root = root / "certification" / "test_cases"
    out = root / "certification" / "traceability" / "VRP-RTM-001.md"

    rows = [
        "# VRP-RTM-001 — Requirements Traceability Matrix",
        "",
        "Auto-generated by `Tools/cert/gen_traceability.py`.",
        "",
        "## High-Level Requirements (HLRD)",
        "",
        "| Req ID | DAL | Module | Verify | Tests |",
        "|---|---|---|---|---|",
    ]

    for req_file in sorted(hlrd_dir.glob("VRP-HLRD-*.yaml")):
        req = parse_simple_yaml(req_file.read_text())
        tests = req.get("tests", [])
        test_str = ", ".join(tests) if isinstance(tests, list) else str(tests)
        rows.append(
            f"| {req.get('id', '')} | {req.get('dal', '')} | {req.get('module', '')} | "
            f"{req.get('verify', '')} | {test_str} |"
        )

    if mlrd_root.exists():
        rows.extend(
            [
                "",
                "## Module Requirements (MLRD)",
                "",
                "| Req ID | Parent | DAL | Module | Verify | Tests |",
                "|---|---|---|---|---|---|",
            ]
        )
        for mlrd_file in sorted(mlrd_root.glob("*/VRP-MLRD-*.yaml")):
            req = parse_simple_yaml(mlrd_file.read_text())
            tests = req.get("tests", [])
            test_str = ", ".join(tests) if isinstance(tests, list) else str(tests)
            rows.append(
                f"| {req.get('id', '')} | {req.get('parent', '')} | {req.get('dal', '')} | "
                f"{req.get('module', '')} | {req.get('verify', '')} | {test_str} |"
            )

    rows.extend(
        [
            "",
            "## Low-Level Requirements — Libraries (LLRD)",
            "",
            "| Req ID | Parent | DAL | ArduPilot | VRP Module | Status | Phase | Verify |",
            "|---|---|---|---|---|---|---|---|",
        ]
    )

    wired_count = 0
    for llrd_file in sorted(llrd_root.glob("*/VRP-LLRD-*.yaml")):
        req = parse_simple_yaml(llrd_file.read_text())
        status = req.get("status", "")
        if status == "wired" or req.get("wired") == "true":
            wired_count += 1
        rows.append(
            f"| {req.get('id', '')} | {req.get('parent', '')} | {req.get('dal', '')} | "
            f"`{req.get('ap_equivalent', '')}` | `{req.get('vrp_module', '').split('/')[-1]}` | "
            f"{status} | {req.get('phase', '')} | {req.get('verify', '')} |"
        )

    if tc_root.exists():
        tc_files = sorted(tc_root.glob("VRP-TC-*.md"))
        if tc_files:
            rows.extend(
                [
                    "",
                    "## Test Cases (VRP-TC)",
                    "",
                    "| TC ID | Document |",
                    "|---|---|",
                ]
            )
            for tc in tc_files:
                rows.append(f"| {tc.stem} | [`{tc.name}`](../test_cases/{tc.name}) |")

    dal_summary: dict[str, int] = {}
    for llrd_file in llrd_root.glob("*/VRP-LLRD-*.yaml"):
        req = parse_simple_yaml(llrd_file.read_text())
        dal = req.get("dal", "?")
        dal_summary[dal] = dal_summary.get(dal, 0) + 1

    rows.extend(
        [
            "",
            "## Riepilogo DAL librerie",
            "",
            "| DAL | Conteggio |",
            "|:---:|---:|",
        ]
    )
    for dal in sorted(dal_summary.keys()):
        rows.append(f"| {dal} | {dal_summary[dal]} |")

    rows.extend(
        [
            "",
            "## Riepilogo certificazione",
            "",
            f"- Librerie **wired** (flight loop): **{wired_count}**",
            f"- LLRD totali: **{len(list(llrd_root.glob('*/VRP-LLRD-*.yaml')))}**",
            f"- HLRD: **{len(list(hlrd_dir.glob('VRP-HLRD-*.yaml')))}**",
            "- Copter SITL gate: `VRP-COPTER-ALL PASS`",
            "- Status document: [`VRP-CERT-STATUS.md`](../VRP-CERT-STATUS.md)",
        ]
    )

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(rows) + "\n")
    print(f"written: {out} ({len(list(llrd_root.glob('*/VRP-LLRD-*.yaml')))} LLRD rows, wired={wired_count})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
