// Auto-generated by Tools/vrp_hwdef_parser.py
#pragma once
#define VRP_APJ_BOARD_ID "AP_HW_VRESP32_V1"
#define VRP_USB_VENDOR "0x27AC"
#define VRP_USB_PRODUCT "0x1851"
#define VRP_MCU "ESP32"
#define VRP_TARGET_HAL "HAL_ESP32"
#define VRP_IMU "MPU6000"
#define VRP_BARO "BMP280"
#define VRP_COMPASS "QMC5883L"
#define VRP_STORAGE "SPI_FLASH"
#define VRP_XTAL_HZ 40000000
#define VRP_FLASH_SIZE 4194304
#define VRP_WIFI_ENABLED 1
