#!/usr/bin/env python3
"""Simple hwdef.vrp parser for generated board headers."""

from __future__ import annotations

import argparse
from pathlib import Path


def parse_hwdef(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split(maxsplit=1)
        if len(parts) == 2:
            data[parts[0]] = parts[1]
    return data


def emit_header(cfg: dict[str, str]) -> list[str]:
    out = [
        "// Auto-generated by Tools/vrp_hwdef_parser.py",
        "#pragma once",
        f'#define VRP_APJ_BOARD_ID "{cfg.get("APJ_BOARD_ID", "UNKNOWN")}"',
        f'#define VRP_USB_VENDOR "{cfg.get("USB_VENDOR", "0x0000")}"',
        f'#define VRP_USB_PRODUCT "{cfg.get("USB_PRODUCT", "0x0000")}"',
        f'#define VRP_MCU "{cfg.get("MCU", "UNKNOWN")}"',
        f'#define VRP_TARGET_HAL "{cfg.get("TARGET_HAL", "HAL_ChibiOS")}"',
    ]
    for key, macro in (
        ("IMU", "VRP_IMU"),
        ("BARO", "VRP_BARO"),
        ("COMPASS", "VRP_COMPASS"),
        ("STORAGE", "VRP_STORAGE"),
    ):
        if key in cfg:
            out.append(f'#define {macro} "{cfg[key]}"')
    for key, macro in (
        ("XTAL_HZ", "VRP_XTAL_HZ"),
        ("FLASH_SIZE", "VRP_FLASH_SIZE"),
        ("WIFI_ENABLED", "VRP_WIFI_ENABLED"),
    ):
        if key in cfg:
            out.append(f"#define {macro} {cfg[key]}")
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True, type=Path)
    ap.add_argument("--output", required=True, type=Path)
    args = ap.parse_args()

    cfg = parse_hwdef(args.input)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(emit_header(cfg)) + "\n")
    print(f"generated: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
